### PR TITLE
Fixed the misspelling of the word 'article' 27 times

### PR DESCRIPTION
**Pull request by Midlevel-deity**

### CODE REVIEW

**Comment by Midlevel-deity** [comment]
Hello?  What's taking so long to merge this?  It's literally just a spelling fix.....

**Comment by jvscrptr** [comment]
took a week off to deal with personal stuff @Midlevel-deity

**Comment by Midlevel-deity** [comment]
Fixed the merge conflict since your last push.  You corrected a few of the misspellings, but there are still more to fix if you'd like to just go ahead an merge this pull request.....

**Comment by jvscrptr** [comment]
@Midlevel-deity not merging as all is fine and u changed a color i dont want changed thx anyway i will be closeing this as of now

**Comment by Midlevel-deity** [comment]
@jvscrptr I didn't change any colors at all.  I literally only changed the spellings of Artical.

**Comment by jvscrptr** [comment]
@midlevel-deity yea no srry viewed a commit that i made and mis-took as urs but i viewed urs and no longer needed cuz the rest wont be viewable in browser only on here so

**Pull request closed without merging**
